// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19VqJcgVKGst9GDvy-jQI_aQMMzZ59BE',
    appId: '1:921096057850:web:064c49c3f82a0f48edaa43',
    messagingSenderId: '921096057850',
    projectId: 'foodordertugas',
    authDomain: 'foodordertugas.firebaseapp.com',
    storageBucket: 'foodordertugas.appspot.com',
    measurementId: 'G-D6P4P8GNBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_Kfw0JMRHL1v0Xme2hfEGIihE0scWpo',
    appId: '1:921096057850:android:88c2e832d2697dc2edaa43',
    messagingSenderId: '921096057850',
    projectId: 'foodordertugas',
    storageBucket: 'foodordertugas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkLOvYRlM5Njm7dGgHKCwCOheItbr9324',
    appId: '1:921096057850:ios:cc9d1d93feeb8e5cedaa43',
    messagingSenderId: '921096057850',
    projectId: 'foodordertugas',
    storageBucket: 'foodordertugas.appspot.com',
    iosBundleId: 'com.example.projekutslagi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkLOvYRlM5Njm7dGgHKCwCOheItbr9324',
    appId: '1:921096057850:ios:cc9d1d93feeb8e5cedaa43',
    messagingSenderId: '921096057850',
    projectId: 'foodordertugas',
    storageBucket: 'foodordertugas.appspot.com',
    iosBundleId: 'com.example.projekutslagi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19VqJcgVKGst9GDvy-jQI_aQMMzZ59BE',
    appId: '1:921096057850:web:35a9b417032ba357edaa43',
    messagingSenderId: '921096057850',
    projectId: 'foodordertugas',
    authDomain: 'foodordertugas.firebaseapp.com',
    storageBucket: 'foodordertugas.appspot.com',
    measurementId: 'G-KKSEBZ6S8V',
  );
}
